### PR TITLE
Add site_metadata.json example

### PR DESCRIPTION
**Pull request by johnrandolph**

### CODE REVIEW

**Review by grafnu — COMMENTED** [review]
Please see the comments in https://github.com/faucetsdn/udmi_site_model/pull/1, also I think you need to delete the site_defaults.json file (really this is a move, not a new file!)

**Comment by johnrandolph** [comment]
I don't think site_defaults is, in aggregate from all these commits, still here. 
Wasn't that covered in 
https://github.com/faucetsdn/udmi_site_model/pull/2/commits/0c385ce388833360541934a824c1ad8b83ab705a  ?

**Comment by grafnu** [comment]
I'm not sure what that specific commit is -- I just know it was merged with
https://github.com/faucetsdn/udmi_site_model/pull/1  -- and it's in the
repo main branch if you look at the top level.

**Comment by johnrandolph** [comment]
Closing to start fresh

**Pull request closed without merging**
